### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by guipasmoi** [Zubnix/skia-wasm-port#4]
Have you done any work to support images. If you are not, i will give it a try. Anyway i would  appreciate some help (C++ is not my expertise).

PS: you did an awesome job.
i used your work. without the binding and it worked perfectly.

**Comment by Zubnix** [comment]
I assume you mean (skia) image loading from an external source? SkImage is currently only implemented as coming from an SkSurface (snapshot) so you would need to add the mapping needed to load an arbitray image data. I'm not sure which supported image formats are currently include in the provided bitcode in the repository, so your mileage may vary.

I guess https://github.com/google/skia/blob/master/include/core/SkImage.h#L175 is what you need.

The procedure to get the image data and passing it to the skia library should then very much the same as the font loading example.

As for the C++, I'd never done any C++ when I started this project. So my advice on that part won't be of much help I'm afraid. :)
